/** Fortunes: the saying, and (on the next line) who said it. */
export const FORTUNES = [
  'Talk is cheap. Show me the code.\n    Linus Torvalds',
  'Any sufficiently advanced technology is\nindistinguishable from magic.\n    Arthur C. Clarke',
  'First, solve the problem. Then, write the code.\n    John Johnson',
  'Simplicity is prerequisite for reliability.\n    Edsger W. Dijkstra',
  'Programs must be written for people to read,\nand only incidentally for machines to execute.\n    Harold Abelson',
  'The best way to predict the future is to invent it.\n    Alan Kay',
  'Make it work, make it right, make it fast.\n    Kent Beck',
  'There are only two hard things in computer science:\ncache invalidation and naming things.\n    Phil Karlton',
  'It works on my machine.\n    every developer, at some point',
  'Weeks of coding can save you hours of planning.\n    unknown',
  'The cogs turn whether you watch them or not.\n    the escapement',
  'A clock that has stopped is right twice a day.\nA clock that runs slow is never right.\n    old watchmaker saying',
  'Measure twice, cut once.\n    every workshop wall',
  'The kettle is always on.\n    Ryhox',
  'Deleted code is debugged code.\n    Jeff Sickel',
  'Before software can be reusable\nit first has to be usable.\n    Ralph Johnson',
  'In theory, theory and practice are the same.\nIn practice, they are not.\n    unknown',
  'You will find a missing semicolon today.\n    your fortune',
  'A long scroll lies ahead of you. Enjoy the ride.\n    your fortune',
  'Your next commit message will be "fix".\n    your fortune',
  'Brass does not rust. It gets a patina.\n    the workshop',
  'Good design is as little design as possible.\n    Dieter Rams',
  'The details are not the details.\nThey make the design.\n    Charles Eames',
  'Real artists ship.\n    Steve Jobs',
];

export const JOKES = [
  'why do programmers prefer dark mode?\nbecause light attracts bugs.',
  'there are 10 kinds of people in the world:\nthose who understand binary and those who do not.',
  'a SQL query walks into a bar, goes up to two tables\nand asks: can i join you?',
  'why did the developer go broke?\nbecause he used up all his cache.',
  'how many programmers does it take to change a light bulb?\nnone. that is a hardware problem.',
  'i would tell you a UDP joke,\nbut you might not get it.',
  'knock knock.\nrace condition.\nwho is there?',
  'why was the javascript developer sad?\nbecause he did not Node how to Express himself.',
  'what is a clockmaker\'s favourite snack?\nwatch crisps. they come in seconds.',
  'my code does not have bugs.\nit has random features.',
  'why do cogs never argue?\nthey always find a way to mesh.',
  'to understand recursion,\nyou must first understand recursion.',
];

export const EIGHT_BALL = [
  'it is certain.',
  'without a doubt.',
  'yes, definitely.',
  'you may rely on it.',
  'as i see it, yes.',
  'most likely.',
  'outlook good.',
  'signs point to yes.',
  'reply hazy, try again.',
  'ask again later.',
  'better not tell you now.',
  'cannot predict now.',
  'concentrate and ask again.',
  "don't count on it.",
  'my reply is no.',
  'my sources say no.',
  'outlook not so good.',
  'very doubtful.',
];

export const HANGMAN_WORDS = [
  'escapement',
  'pendulum',
  'flywheel',
  'sprocket',
  'gearbox',
  'piston',
  'boiler',
  'rivet',
  'brass',
  'copper',
  'lantern',
  'compass',
  'telegraph',
  'phosphor',
  'terminal',
  'keyboard',
  'javascript',
  'typescript',
  'shader',
  'texture',
  'framebuffer',
  'viewport',
  'function',
  'variable',
  'recursion',
  'algorithm',
  'compiler',
  'pixel',
  'vertex',
  'portfolio',
  'workshop',
  'vinyl',
];
